baseUrl: "https://michael.biven.org/"
languageCode: en-us
theme: hello-friend
copyright: >
  <span>Copyright &copy; 2006-2020 <a href="https://michael.biven.org">Michael Biven</a>. All Rights Reserved.</br>
  Powered by <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a> and theme by <a href="https://twitter.com/panr" target="_blank" rel="noopener">panr</a></span>
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # "dark" or "light"
  defaultTheme: light
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 4

languages:
  en:
    title: Michael Biven
    subtitle: I build and run infrastructure.
    keywords: ''
    menuMore: Show more
    writtenBy: Written by
    readOtherPosts: Read other posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    
    params:
      logo:
        logoText: "$ whois Michael Biven"
        logoHomeLink: /
    
    menu:
      main:
      - identifier: about
        name: About
        url: "https://michael.biven.org"
        weight: 10
      
 